#
###################################
# Site wide configuration
####################################
#
title: Rehan Guha -Portfolio & Blog
email: rehanguha29@gmail.com
description: Portfolio and Blog
url: https://rehanguha.github.io
repository: rehanguha/rehanguha.github.io
keywords: ["Rehan", "R. Guha", "Joel", "Machine Learning", "Resume"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Kolkata
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
# permalink:         /articles/:year-:month/:title
permalink:         /articles/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Rehan Guha"
  avatar: profile_photo.png
  job: "Author -  ML Researcher"
  bio: "To talk about myself is a bit of a challenge for me as I more comfortable while talking about my work and discussing about Philosophy & Science."
  email: "rehanguha29@gmail.com"
  disqus-shortname: "rehanguha"
  twitter: "rehan_guha"
  facebook: 
  google:
    plus: #username
    analytics: "UA-134752950-1"
    ga4: "G-6KBF2J9YMF"
    tagmanager: "GTM-WBZWLRV"
    ad-client:
    ad-slot:
  bing-verify:
  github: "rehanguha"
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: "rehanguha"
  skype: #username
  xing: #username
  instagram: "rehan.guha"
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: rehanguha
  500px: #username
  codepen: #username
  reddit:
  telegram: #username
